### ISSUE TITLE
Build issue: Parcel/Watcher causing issue while building this project

### ISSUE THREAD

**Issue by msrajput8894** [msrajput8894/Forkify1#1]
Parcel/Watcher is causing the issues while building this project which needs to be fixed.

**Comment by msrajput8894** [comment]
Build is failing due to following error.
Build command from Netlify app                                
12:22:17 AM: ────────────────────────────────────────────────────────────────
12:22:17 AM: ​
12:22:17 AM: $ npm run build
12:22:17 AM: > forkify@1.0.0 build
12:22:17 AM: > parcel build index.html --dist-dir ./dist
12:22:18 AM: Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-linux-x64-glibc. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
12:22:18 AM:     at Object.<anonymous> (/opt/build/repo/node_modules/@parcel/watcher/index.js:26:13)
12:22:18 AM:     at Module._compile (node:internal/modules/cjs/loader:1364:14)
12:22:18 AM:     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
12:22:18 AM:     at Module.load (node:internal/modules/cjs/loader:1203:32)
12:22:18 AM:     at Module._load (node:internal/modules/cjs/loader:1019:12)
12:22:18 AM:     at Module.require (node:internal/modules/cjs/loader:1231:19)
12:22:18 AM:     at require (node:internal/modules/helpers:177:18)
12:22:18 AM:     at Object.<anonymous> (/opt/build/repo/node_modules/@parcel/fs/lib/index.js:9:28)
12:22:18 AM:     at Module._compile (node:internal/modules/cjs/loader:1364:14)
12:22:18 AM:     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
12:22:18 AM: ​
12:22:18 AM: "build.command" failed                                        
12:22:18 AM: ────────────────────────────────────────────────────────────────
12:22:18 AM: ​
12:22:18 AM:   Error message
12:22:18 AM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
12:22:18 AM: ​
12:22:18 AM:   Error location
12:22:18 AM:   In Build command from Netlify app:
12:22:18 AM:   npm run build
12:22:18 AM: ​
12:22:18 AM:   Resolved config
12:22:18 AM:   build:
12:22:18 AM:     command: npm run build
12:22:18 AM:     commandOrigin: ui
12:22:18 AM:     publish: /opt/build/repo/dist
12:22:18 AM:     publishOrigin: ui
12:22:18 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
12:22:18 AM: Failing build: Failed to build site
12:22:18 AM: Finished processing build request in 21.996s

**Comment by msrajput8894** [comment]
fixed the issue by reinstalling the node_modules and package.json, and even installed the parcel/watcher
